### ISSUE TITLE
NPE on Android Q

### ISSUE THREAD

**Issue by DevanshiVyas** [prakhar1989/friendlychat#3]
I keep forgetting some of the basic setup work for adding a new rule (thanks to @bmish for catching my mistakes). In order to save us from my forgetfulness we should add a test to ensure this kind of thing doesn't slip.

Basically to assert the following:

All files under lib/rules/ (except base.js and index.js) exist as values in the lib/rules/index.js reexport.
All files under lib/rules/ (same exception) have a corresponding docs/rule/ file.
All files under docs/rule/ have a link from docs/rules.md.

**Comment by DevanshiVyas** [comment]
are you looking at this?

**Comment by DevanshiVyas** [comment]
The test() method executes a search for a match between a regular expression and a specified string. Returns true or false

**Comment by prakhar1989** [comment]
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
